{% set name = "mssql-django" %}
{% set version = "1.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mssql_django-{{ version }}.tar.gz
  sha256: 00b22ea619bc146a15ffe33d5397a861cb7a9b9312c2e058dfd0781b8fe70007

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - django >=3.2,<6.1
    - pyodbc >=3.0
    - pytz

test:
  imports:
    - mssql
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/microsoft/mssql-django
  summary: Django backend for Microsoft SQL Server
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
    - NOTICE.md

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
