{% set name = "mssql-django" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mssql-django-{{ version }}.tar.gz
  sha256: 430b7e19eaec1396c9ab32abb4d3378fec375fb23bf93f61140fdcaaa7052d6c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - django >=3.2,<5.1
    - pyodbc >=3.0
    - pytz

test:
  imports:
    - mssql
    - testapp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/mssql-django
  summary: Django backend for Microsoft SQL Server
  license: BSD-3-Clause
  license_file:
    - NOTICE.md
    - LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
