{% set name = "mssql-django" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mssql-django-{{ version }}.tar.gz
  sha256: 57e83582742ec3a056c7b56330cab5475b8ec8e5c5e2045b017af6cb4dc28649

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.11
    - pip
  run:
    - python >=3.7,<3.11
    - django >=2.2,<4.1
    - pyodbc >=3.0
    - pytz

test:
  imports:
    - mssql
    - testapp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/mssql-django
  summary: Django backend for Microsoft SQL Server
  license: BSD-3-Clause
  license_file:
    - NOTICE.md
    - LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
